### ISSUE TITLE
Upstreamed to typeshed

### ISSUE THREAD

**Issue by Avasam** [kaluluosi/pywin32-stubs#9]
Just letting you know that typeshed now has pywin32 stubs which covers everything in this repo and more. https://github.com/python/typeshed/tree/master/stubs/pywin32
https://pypi.org/project/types-pywin32/

**Comment by kaluluosi** [comment]
so maybe I can remove win32typing.pyi , instead of using types-pywin32. 🤔
As you know , I generate these api stub from chm document. I didn't wrote it all by my hand. 😓
chm doc is not perfect. some param typing missing or some is wrong name. 😢
maybe you can create a new repo, generate stub just from win32 c++?😘
I think pywin32-stubs is usefull for some people. but this project i think didn't deserve. we need a more complete one.

**Comment by kaluluosi** [comment]
I will make a try later. It's offical pywin32 stubs and typing. Maybe I can shut this poor repo/package down ,and use offical one instead.
